import { config } from "dotenv";
config({ path: ".env.local" });

import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "../lib/db/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

async function seed() {
  console.log("🌱 Seeding database...");

  // ── News ────────────────────────────────────────────────────────────────────
  await db.insert(schema.newsItems).values([
    {
      title: "Brașovul pregătește cea mai mare investiție în transport public din ultimii 20 de ani",
      excerpt: "Primăria Brașov a anunțat achiziția a 50 de autobuze electrice și modernizarea a 30 de stații de transport public. Investiția totală se ridică la 85 de milioane de euro și va transforma complet mobilitatea urbană.",
      sourceUrl: "https://bzt.ro/articol-exemplu-1",
      sourceName: "BZT.ro",
      author: "Redacția BZT",
      publishedAt: new Date("2024-12-10"),
      imageUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80",
      category: "Actualitate",
      slug: "brasovul-pregateste-cea-mai-mare-investitie-transport-2024-12-10",
      status: "published",
    },
    {
      title: "Festivalul de Film de la Brașov revine cu o ediție record: peste 200 de filme din 40 de țări",
      excerpt: "Cea de-a 15-a ediție a Festivalului de Film de la Brașov va aduce în oraș regizori și actori de renume internațional. Evenimentul se va desfășura în perioada 15-22 iunie în mai multe locații din centrul istoric.",
      sourceUrl: "https://bzt.ro/articol-exemplu-2",
      sourceName: "BZT.ro",
      author: "Maria Ionescu",
      publishedAt: new Date("2024-12-09"),
      imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
      category: "Cultură",
      slug: "festivalul-film-brasov-editie-record-2024-12-09",
      status: "published",
    },
    {
      title: "Pârtia Poiana Brașov deschide sezonul cu zăpadă artificială pe toate traseele",
      excerpt: "Administratorii domeniului schiabil Poiana Brașov anunță deschiderea sezonului de schi. Toate cele 12 pârtii sunt acoperite cu zăpadă artificială, iar telescaunele funcționează la capacitate maximă.",
      sourceUrl: "https://bzt.ro/articol-exemplu-3",
      sourceName: "Transilvania Reporter",
      author: "Andrei Popa",
      publishedAt: new Date("2024-12-08"),
      imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80",
      category: "Sport",
      slug: "partia-poiana-brasov-deschide-sezonul-2024-12-08",
      status: "published",
    },
    {
      title: "Noi locuri de muncă în Brașov: o companie IT germană deschide birou cu 300 de angajați",
      excerpt: "Compania germană TechGroup AG a ales Brașovul pentru cel de-al doilea centru de dezvoltare din România. Biroul va angaja inițial 300 de specialiști IT, cu planuri de extindere la 800 în următorii trei ani.",
      sourceUrl: "https://bzt.ro/articol-exemplu-4",
      sourceName: "BZT.ro",
      author: "Redacția BZT",
      publishedAt: new Date("2024-12-07"),
      imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      category: "Business",
      slug: "companie-it-germana-deschide-birou-brasov-2024-12-07",
      status: "published",
    },
    {
      title: "Spitalul Județean Brașov primește aparatură medicală de ultimă generație",
      excerpt: "Un tomograf de nouă generație și un sistem de imagistică prin rezonanță magnetică au fost instalate la Spitalul Județean Brașov. Echipamentele, în valoare de 4 milioane de euro, vor reduce timpul de diagnostic.",
      sourceUrl: "https://bzt.ro/articol-exemplu-5",
      sourceName: "Monitorul Expres",
      publishedAt: new Date("2024-12-06"),
      imageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&q=80",
      category: "Sănătate",
      slug: "spitalul-judetean-brasov-aparatura-noua-2024-12-06",
      status: "published",
    },
    {
      title: "Târgul de Crăciun din Piața Sfatului — cel mai frumos din România, potrivit unui top european",
      excerpt: "Târgul de Crăciun din Brașov a fost inclus pentru al treilea an consecutiv în topul celor mai frumoase târguri de Crăciun din Europa, ocupând locul 8 într-un clasament realizat de European Best Destinations.",
      sourceUrl: "https://bzt.ro/articol-exemplu-6",
      sourceName: "BZT.ro",
      author: "Elena Dumitrescu",
      publishedAt: new Date("2024-12-05"),
      imageUrl: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=800&q=80",
      category: "Actualitate",
      slug: "targ-craciun-brasov-top-european-2024-12-05",
      status: "published",
    },
  ]).onConflictDoNothing();

  console.log("✅ News seeded");

  // ── Events ───────────────────────────────────────────────────────────────────
  await db.insert(schema.events).values([
    {
      title: "Târgul de Crăciun Brașov 2024",
      description: "Cel mai iubit eveniment al iernii brașovene revine în Piața Sfatului! Te așteptăm cu standuri cu meșteșuguri tradiționale, mâncare și băuturi specifice sezonului, concerte live și spectacole pentru copii. Moș Crăciun va fi prezent în fiecare weekend.",
      slug: "targul-de-craciun-brasov-2024",
      startsAt: new Date("2024-12-01"),
      endsAt: new Date("2024-12-26"),
      locationName: "Piața Sfatului",
      address: "Piața Sfatului, Brașov",
      latitude: "45.6427",
      longitude: "25.5887",
      category: "Cultural",
      imageUrl: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=800&q=80",
      isFree: true,
      status: "published",
    },
    {
      title: "Concert de Anul Nou — Orchestra Filarmonicii Brașov",
      description: "Întâmpinați Noul An cu un concert de gală susținut de Orchestra Filarmonicii Brașov. Pe program: lucrări de Strauss, Brahms și compozitori români. Dirijor invitat: Cristian Mandeal. Locuri limitate — rezervați din timp!",
      slug: "concert-anul-nou-filarmonica-brasov-2025",
      startsAt: new Date("2025-01-01T20:00:00"),
      endsAt: new Date("2025-01-01T22:30:00"),
      locationName: "Filarmonica Brașov",
      address: "Str. Hirscher 10, Brașov",
      latitude: "45.6415",
      longitude: "25.5890",
      category: "Muzică",
      imageUrl: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&q=80",
      isFree: false,
      price: "80",
      currency: "RON",
      status: "published",
    },
    {
      title: "Maraton Brașov 2025 — ediția de iarnă",
      description: "Prima ediție de iarnă a Maratonului Brașov vă invită să alergați prin cel mai frumos oraș din Ardeal. Trasee disponibile: 5 km, 10 km și semi-maraton. Toți participanții primesc medalie și tricou personalizat.",
      slug: "maraton-brasov-editia-iarna-2025",
      startsAt: new Date("2025-02-15T09:00:00"),
      locationName: "Parcul Central Brașov",
      address: "Parcul Central, Brașov",
      latitude: "45.6580",
      longitude: "25.6012",
      category: "Sport",
      imageUrl: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
      isFree: false,
      price: "50",
      currency: "RON",
      status: "published",
    },
    {
      title: "Expoziție: Brașovul Medieval în Fotografii",
      description: "O călătorie vizuală prin istoria Brașovului, de la cetate medievală la oraș modern. Expoziția prezintă peste 150 de fotografii de arhivă și contemporane, unele expuse public pentru prima dată.",
      slug: "expozitie-brasovul-medieval-fotografii-2025",
      startsAt: new Date("2025-01-15"),
      endsAt: new Date("2025-03-15"),
      locationName: "Muzeul de Artă Brașov",
      address: "Bulevardul Eroilor 21, Brașov",
      latitude: "45.6497",
      longitude: "25.6065",
      category: "Cultural",
      imageUrl: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800&q=80",
      isFree: false,
      price: "15",
      currency: "RON",
      status: "published",
    },
    {
      title: "Workshop Fotografie de Peisaj — Tampa și împrejurimi",
      description: "Alătură-te fotografului profesionist Alexandru Marin pentru o zi întreagă de fotografie pe Tampa și în Poiana Brașov. Vei învăța tehnici de fotografie de peisaj, compoziție și editare foto. Maxim 12 participanți.",
      slug: "workshop-fotografie-peisaj-tampa-2025",
      startsAt: new Date("2025-01-25T08:00:00"),
      endsAt: new Date("2025-01-25T17:00:00"),
      locationName: "Cabana Vânătorilor (punct de plecare)",
      address: "Str. Vânătorilor, Brașov",
      category: "Educație",
      imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      isFree: false,
      price: "200",
      currency: "RON",
      status: "published",
    },
  ]).onConflictDoNothing();

  console.log("✅ Events seeded");

  // ── Places ───────────────────────────────────────────────────────────────────
  await db.insert(schema.places).values([
    {
      name: "Cafenea Turnul Negru",
      description: "Cafenea artizanală în inima centrului istoric, la umbra Turnului Negru. Servim cafea de specialitate din boabe selectate din Ethiopia, Colombia și Brazilia. Micul dejun servit toată ziua, inclusiv opțiuni vegane.",
      slug: "cafenea-turnul-negru",
      category: "Cafenea",
      address: "Str. Dupa Ziduri 3, Brașov",
      phone: "0726 123 456",
      website: "https://turnulnegru.ro",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80"]),
      status: "published",
    },
    {
      name: "Restaurant Cetatea",
      description: "Restaurant tradițional românesc cu vedere spectaculoasă spre Cetatea Brașovului. Specialitățile casei includ sarmale în foi de viță, ciorbă de burtă și tochitură moldovenească, preparate după rețete de familie.",
      slug: "restaurant-cetatea-brasov",
      category: "Restaurant",
      address: "Aleea Tiberiu Brediceanu 2, Brașov",
      phone: "0268 456 789",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80"]),
      status: "published",
    },
    {
      name: "Librărie & Bistro Pagina",
      description: "Librărie independentă cu bistro integrat — cumpără o carte și citește-o la o cafea sau un pahar de vin. Organizăm săptămânal lansări de carte, cluburi de lectură și seri de poezie. Deschis zilnic 09:00–22:00.",
      slug: "librarie-bistro-pagina-brasov",
      category: "Cafenea",
      address: "Str. Mureșenilor 15, Brașov",
      phone: "0744 987 654",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80"]),
      status: "published",
    },
    {
      name: "Studio FitLife Brașov",
      description: "Sală de fitness modernă cu echipamente premium, clase de group fitness (yoga, pilates, zumba, spinning) și antrenori personali certificați. Abonament lunar de la 150 RON. Prima ședință gratuită!",
      slug: "studio-fitlife-brasov",
      category: "Servicii",
      address: "Str. Lungă 45, Brașov",
      phone: "0722 333 444",
      website: "https://fitlife-brasov.ro",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80"]),
      status: "published",
    },
    {
      name: "Brutăria Ardeleană",
      description: "Pâine coaptă în cuptor cu lemne după rețete tradiționale ardelene. Deschisă din 1998, brutăria noastră produce zilnic: pâine neagră, pâine cu semințe, cozonaci și colaci. Comenzi pentru evenimente la cerere.",
      slug: "brutaria-ardeleana-brasov",
      category: "Magazin",
      address: "Str. Harmanului 8, Brașov",
      phone: "0268 111 222",
      status: "published",
    },
    {
      name: "Galerie de Artă Tampa",
      description: "Galerie de artă contemporană dedicată artiștilor locali și din Transilvania. Expoziții rotative lunar, vânzare de lucrări originale, workshop-uri de pictură și sculptură pentru adulți și copii.",
      slug: "galerie-arta-tampa-brasov",
      category: "Cultură",
      address: "Str. Republicii 22, Brașov",
      phone: "0733 555 666",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&q=80"]),
      status: "published",
    },
  ]).onConflictDoNothing();

  console.log("✅ Places seeded");

  // ── Listings ─────────────────────────────────────────────────────────────────
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  await db.insert(schema.listings).values([
    {
      title: "iPhone 14 Pro 256GB — Negru Cosmic, impecabil",
      description: "Vând iPhone 14 Pro 256GB în stare impecabilă, folosit 8 luni. Vine cu toate accesoriile originale (cablu, adaptor), cutia originală și folie de sticlă aplicată. Baterie 94%. Nu are zgârieturi sau lovituri. Motiv vânzare: am primit telefon de serviciu.",
      slug: "iphone-14-pro-256gb-negru-cosmic-2024-12-10",
      price: "4200",
      currency: "RON",
      category: "Electronice",
      condition: "used",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800&q=80"]),
      location: "Brașov, Centru",
      contactPhone: "0722 111 222",
      status: "active",
      expiresAt,
    },
    {
      title: "Canapea extensibilă 3 locuri + fotoliu — gri antracit",
      description: "Vând canapea extensibilă cu ladă de depozitare (3 locuri) și fotoliu asortate, culoare gri antracit. Cumpărate acum 2 ani de la Mobexpert, în stare foarte bună. Dimensiuni canapea: 220x95 cm. Motivul vânzării: mutare.",
      slug: "canapea-extensibila-3-locuri-fotoliu-gri-2024-12-09",
      price: "1800",
      currency: "RON",
      category: "Mobilă",
      condition: "used",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"]),
      location: "Brașov, Astra",
      contactPhone: "0744 333 555",
      status: "active",
      expiresAt,
    },
    {
      title: "Apartament 2 camere de închiriat — Tractorul, mobilat complet",
      description: "Închiriez apartament 2 camere în cartierul Tractorul, etaj 4/8, mobilat și utilat complet. Bloc reabilitat termic, interfon, parcare disponibilă. Suprafață 54 mp. Disponibil de la 1 ianuarie. Preț negociabil pentru contract pe termen lung.",
      slug: "apartament-2-camere-inchiriat-tractorul-mobilat-2024-12-08",
      price: "450",
      currency: "EUR",
      category: "Imobiliare",
      condition: "not_applicable",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"]),
      location: "Brașov, Tractorul",
      contactPhone: "0726 777 888",
      contactEmail: "chirii.brasov@gmail.com",
      status: "active",
      expiresAt,
    },
    {
      title: "Bicicletă MTB Trek Marlin 7 — 2022, talie M",
      description: "Vând bicicletă MTB Trek Marlin 7, an fabricație 2022, talie M (potrivit pentru înălțime 170-180 cm). Componente: Shimano Deore 1x12, furculiță RockShox Judy 100mm. Rulată aproximativ 800 km, service recent efectuat.",
      slug: "bicicleta-mtb-trek-marlin-7-2022-talie-m-2024-12-07",
      price: "3500",
      currency: "RON",
      category: "Electronice",
      condition: "used",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"]),
      location: "Brașov, Schei",
      contactPhone: "0733 999 000",
      status: "active",
      expiresAt,
    },
    {
      title: "Mașină de spălat Bosch 8kg — A+++, livrare inclusă",
      description: "Vând mașină de spălat Bosch Serie 4, 8 kg, clasa energetică A+++. Cumpărată în 2021, funcționează perfect. Am cumpărat una mai mare. Include transport și deconectare din instalație. Garanție comercială 6 luni.",
      slug: "masina-spalat-bosch-8kg-a-plus-plus-plus-2024-12-06",
      price: "1100",
      currency: "RON",
      category: "Electronice",
      condition: "used",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&q=80"]),
      location: "Brașov, Bartolomeu",
      contactPhone: "0745 444 666",
      status: "active",
      expiresAt,
    },
    {
      title: "Meditații matematică — profesor cu 15 ani experiență",
      description: "Ofer meditații la matematică pentru elevi de gimnaziu și liceu (cls. V-XII). Pregătire pentru BAC, olimpiade și admitere facultate. Metodă personalizată, rezultate garantate. Sediul meu sau online. Prima ședință gratuită.",
      slug: "meditatii-matematica-profesor-15-ani-experienta-2024-12-05",
      price: "80",
      currency: "RON",
      category: "Servicii",
      condition: "not_applicable",
      location: "Brașov (toate cartierele) + online",
      contactPhone: "0721 555 777",
      contactEmail: "prof.matematica.brasov@gmail.com",
      status: "active",
      expiresAt,
    },
    {
      title: "Combinator frigorific Samsung 400L — negru mat",
      description: "Vând combinator Samsung 400L, culoare negru mat, clasa A+. Cumpărat acum 3 ani. Funcționează perfect, fără zgomote. Include sertar pentru legume și fructe, distribuitor de apă. Disponibil pentru ridicare din Brașov, Calea București.",
      slug: "combinator-frigorific-samsung-400l-negru-mat-2024-12-04",
      price: "1300",
      currency: "RON",
      category: "Electronice",
      condition: "used",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80"]),
      location: "Brașov, Calea București",
      contactPhone: "0766 222 333",
      isAssisted: true,
      staffConsentTicked: true,
      status: "active",
      expiresAt,
    },
    {
      title: "Jachetă ski Salomon — mărimea L, roșu, sezon 2023",
      description: "Vând jachetă de ski Salomon, mărimea L, culoare roșu. Folosită doar 2 sezoane, în stare excelentă. Membrană impermeabilă 20.000mm, termoizolație 80g. Ideală pentru schi și activități outdoor de iarnă.",
      slug: "jacheta-ski-salomon-marimea-l-rosu-2024-12-03",
      price: "500",
      currency: "RON",
      category: "Haine",
      condition: "used",
      imagesJson: JSON.stringify(["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80"]),
      location: "Brașov, Poiana Brașov",
      contactPhone: "0788 444 111",
      status: "active",
      expiresAt,
    },
  ]).onConflictDoNothing();

  console.log("✅ Listings seeded");
  console.log("🎉 Done! All mock data inserted.");
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
